### ISSUE TITLE
PyScript support

### ISSUE THREAD

**Issue by ymd-h** [ymd-h/exodide#16]
[PyScript](https://github.com/pyscript/pyscript) is convenient wrapper for Pyodide.

exodide requires Pyodide v0.21a2, however, PyScript uses Pyodide v0.20.1a2.

We will wait until PyScript update.

**Comment by nyckmaia** [comment]
Hi @ymd-h ,

Yesterday the `PyScript` team updated the `Pyodide` to the last version, as you can see [here](https://github.com/pyscript/pyscript/issues/629#event-7085869615).
So I think that will be possible to enable a integration between `PyScript` and `Exodide`.
Right?

Question
----------
Is there anything that need to be change in `Exodide` side to be able to integrate `Exodide` with `PyScript`?

**Comment by ymd-h** [comment]
Hi @nyckmaia,

Thank you for your contribution, however, the CDN script hasn't updated yet.
https://pyscript.net/alpha/pyscript.js
(Please search with `DEFAULT_RUNTIME`.)

Do you know where we get updated one?
(or should we build and host PyScript development version by ourselves?)

**Comment by ymd-h** [comment]
I found `<py-config>` to configure Pyodide runtime.
https://github.com/pyscript/pyscript/blob/main/docs/tutorials/getting-started.md#the-py-config-tag


I tried but couldn't succeed yet.

```html
    <py-config>
      runtimes:
        - src: "https://cdn.jsdelivr.net/pyodide/v0.21.0a2/full/pyodide.js"
          name: "pyodide-0.21.0a2"
          lang: "python"
    </py-config>
```

```
pyconfig.ts:106 Uncaught TypeError: Found non-callable @@iterator
    at PyConfig.connectedCallback (pyconfig.ts:106:34)
    at main.ts:22:34
    at main.ts:35:2
```

**Comment by ymd-h** [comment]
I noticed one more.

The [PR](https://github.com/pyscript/pyscript/commit/ade0dca8f984c47171551c4b671a382d1b74f9ee#diff-cd4ed8d49d3fcdfb3a949dadc21ccd7087c378e203290ca75c9754425f8d037bR2371) didn't update Pyodide version at all, which still uses Pyodide v0.20.1a2.

**Comment by ymd-h** [comment]
We added example with PyScript at [example](https://github.com/ymd-h/exodide/tree/master/example).


> **Note**
> This works only with unstable version of PyScript. We will update after Pyodide update.
